### ISSUE TITLE
Test failure with Ruby 1.9

### ISSUE THREAD

**Issue by Flameeyes** [clemens/delocalize#38]
/usr/bin/ruby19 -I"lib:lib:test" -I"/usr/lib64/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib" "/usr/lib64/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/rake_test_loader.rb" "test/delocalize_test.rb" 
    Run options: 
    
    # Running tests:
    
    ...................F...F..........
    
    Finished tests in 0.409252s, 83.0784 tests/s, 114.8436 assertions/s.
    
      1) Failure:
    test_delocalizes_localized_date_without_year(DelocalizeActiveRecordTest) [/media/repos/flame/git/delocalize/test/delocalize_test.rb:53]:
    <Mon, 19 Oct 2009> expected but was
    <Fri, 19 Oct 2012>.
    
      2) Failure:
    test_delocalizes_localized_time_(non-DST)(DelocalizeActiveRecordTest) [/media/repos/flame/git/delocalize/test/delocalize_test.rb:86]:
    <Sun, 01 Mar 2009 08:00:00 CET +01:00> expected but was
    <Tue, 28 Feb 2012 08:00:00 CET +01:00>.
    
    34 tests, 47 assertions, 2 failures, 0 errors, 0 skips
    rake aborted!
    Command failed with status (2): [/usr/bin/ruby19 -I"lib:lib:test" -I"/usr/l...]
    
    Tasks: TOP => test
    (See full trace by running task with --trace)

**Comment by sobrinho** [comment]
@clemens I think we can ignore that since ruby 1.8 is not maintained anymore.

We probably must set 1-0-beta to be at least on rails 3.2 since we are using strong parameters.

**Comment by clemens** [comment]
Delocalize 1.0 has its own Parameters class in case strong_parameters isn't there – so using it with an older Rails version shouldn't be a problem.

About being able to close it, you're right. :)
