### ISSUE TITLE
Value not delocalized if errors present on attribute

### ISSUE THREAD

**Issue by noniq** [clemens/delocalize#45]
(Spike branch)

Delocalize skips delocalization for attributes with errors (https://github.com/clemens/delocalize/blob/spike/lib/delocalize/action_view.rb#L24). 

In my case there are date fields with a conditional range validation that is deactivated by default. So I can enter any date value and save the record successfully. However, the conditional validation may be triggered later on – and now the already saved value could suddenly become invalid (because it’s outside the range). When I display the edit form at this stage, the date field is not delocalized.

Fixing this would require to remove the line mentioned above and instead add a rescue clause or a type check around the call to `I18n.l` in line 36 (`number_to_precision` in line 34 needs no change as it just returns its argument if it can’t be converted to a number).

Should I prepare a pull request? Or is this use case too obscure to justify the added complexity?

**Comment by sobrinho** [comment]
I think this can be closed since the architectural changes on 1-0-beta.
