### ISSUE TITLE
probable error in methods "clone" and "dup"

### ISSUE THREAD

**Issue by AugustoGu** [clemens/delocalize#56]
I use the gem delocalize and Mongoid with rails 3.2.11.

It works very well.

However using the method ```clone``` or ```dup``` with attributes that use delocalize the dates back one day and loses the decimal number.

example:

```ruby
class Parcel 
   include Mongoid::Document
   include Mongoid::Timestamps
   include Mongoid::MultiParameterAttributes
   include Delocalize::Delocalizable 

   field :description, type: String
   field :date_of_update, type: Date
   field :date_debt, type: Date
   field :original_value, type: BigDecimal

   delocalize date_of_update: :date, date_debt: :date
   delocalize original_value: :number
end
```

```ruby
parcel = Parcel.new
parcel.date_of_update = (Time) 2007-10-01
parcel.date_debt = (Time) 2007-01-01
parcel.original_value = 1011.00
```
Cloning

```ruby
new_parcel = parcel.clone
```

Result:
```ruby
new_parcel.date_of_update  =>  (Time) 2007-09-30
new_parcel.date_debt =>  (Time) 2006-12-31
new_parcel.original_value = 101100
```

Using ```parcel.dup``` the same problem occurs.

Removing delocalize the clone function normally.

**Comment by clemens** [comment]
With the release of 1.0.0, all the logic is now handled on the controller level which makes Delocalize independent of the persistence layer => closed.
