### ISSUE TITLE
Delocalize does not work with Gem best_in_place

### ISSUE THREAD

**Issue by BenStW** [clemens/delocalize#62]
Best_in_place is "The Unobtrusive in Place editing solution".

But it it doesn't work smoothly with delocalize.
When editing a field, the value is not delocalized.

E.g. editing a field with value 2.5 should show "2,5" with locale de, but it shows "2.5".
I also filed an issue at the best_in_place Gem, as I can't estimate where the source  of the problem lays.
https://github.com/bernat/best_in_place/issues/276

**Comment by danieldocki** [comment]
+1

**Comment by clemens** [comment]
I've never used best in place – and I don't think I will in the foreseeable future. If you provide a PR, I'm happy to take a look. If it benefits delocalize as a whole and doesn't break anything, I'm happy to merge it. However, I won't accept any code that messes up delocalize just to support some random gem.

**Comment by clemens** [comment]
Version 1.0.0 doesn't modify the output any longer – so this issue is implicitly resolved.
