### ISSUE TITLE
not working in rails/ruby 2

### ISSUE THREAD

**Issue by kannathasan-railsfactory** [clemens/delocalize#67]
i got the following error when start the rails server in local
"/home/san/.rvm/gems/ruby-2.0.0-p247@r4/gems/activesupport-4.0.0/lib/active_support/core_ext/module/aliasing.rb:32:in `alias_method': undefined method `convert_number_column_value' for class `ActiveRecord::Base' (NameError)
"
my Gemfile:
gem "delocalize",:git => "git://github.com/clemens/delocalize.git",:branch => '0-2-stable'

**Comment by clemens** [comment]
1.0.0 is released which includes support for current Rails and Ruby versions.
