### ISSUE TITLE
thousand problem

### ISSUE THREAD

**Issue by luisfernandos** [clemens/delocalize#68]
the gem fails to convert a number when it is a invalid thousand, for example

R$ 10.23, will generate 1.023, that's because it is missing to test if it is a valid thousand.
In this situation the user typed a wrong value, it should be R$ 10,23 instead of R$ 10.23, however the gem should not convert it to R$ 1.023, shouldn't it raise an exception or give an error???

**Comment by sobrinho** [comment]
I think this can be closed.

We must use a decimal mask on front-end to avoid these kind of errors, there is no way to delocalise guess what the user want with invalid input.
