### ISSUE TITLE
Parsing a localized date

### ISSUE THREAD

**Issue by alex88** [clemens/delocalize#73]
I've installed delocalize and rails-i18n to provide datetime locales, I'm trying to parse this italian date:

Sabato 19 Ottobre 2013 20:30

which is basically

Saturday 19th October 2013 20:30

however DateTIme.parse returns 19 Oct 2014 (it parses just the day number). `I18n.locale` is `:it`, is there something else I have to config to parse the italian date?

**Comment by clemens** [comment]
Sorry about the lack of response – I simply forgot about it. :(

Did you solve your problem and can I close this issue? Otherwise I'm happy to help with further investigation. Also note that delocalize 1.0.0 has been released.
