### ISSUE TITLE
Rails 3.2.22.2 app fails to start: uninitialized constant Delocalize::DelocalizableParameters

### ISSUE THREAD

**Issue by airblade** [clemens/delocalize#80]
Steps to reproduce:

- Take a working Rails 3.2.22.2 app.
- Add `gem 'delocalize', '1.0.0'` to `Gemfile` and `bundle`.
- Reload app.
- Expected: app boots as normal.  Actual:

```
NameError: uninitialized constant Delocalize::DelocalizableParameters
~/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/delocalize-1.0.0/lib/delocalize/railtie.rb:10:in `block (2 levels) in <class:Railtie>'
~/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.22.2/lib/active_support/lazy_load_hooks.rb:36:in `instance_eval'
~/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.22.2/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
~/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.22.2/lib/active_support/lazy_load_hooks.rb:26:in `block in on_load'
~/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.22.2/lib/active_support/lazy_load_hooks.rb:25:in `each'
~/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-3.2.22.2/lib/active_support/lazy_load_hooks.rb:25:in `on_load'
~/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/delocalize-1.0.0/lib/delocalize/railtie.rb:4:in `block in <class:Railtie>'
~/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-3.2.22.2/lib/rails/initializable.rb:30:in `instance_exec'
~/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-3.2.22.2/lib/rails/initializable.rb:30:in `run'
~/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-3.2.22.2/lib/rails/initializable.rb:55:in `block in run_initializers'
~/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-3.2.22.2/lib/rails/initializable.rb:54:in `each'
~/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-3.2.22.2/lib/rails/initializable.rb:54:in `run_initializers'
~/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-3.2.22.2/lib/rails/application.rb:136:in `initialize!'
~/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-3.2.22.2/lib/rails/railtie/configurable.rb:30:in `method_missing'
~/path/to/my/app/config/environment.rb:5:in `<top (required)>'
~/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
~/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
~/path/to/my/app/config.ru:8:in `block in <main>'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/builder.rb:4:in `instance_eval'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/builder.rb:4:in `initialize'
~/path/to/my/app/config.ru:1:in `new'
~/path/to/my/app/config.ru:1:in `<main>'
```

I was able to solve this by adding this line to the top of `lib/delocalize.rb`:

```ruby
require 'delocalize/delocalizable_parameters'
```

**Comment by jdashton** [comment]
+1

**Comment by lucasmncastro** [comment]
+1

**Comment by clemens** [comment]
Sorry for the delayed answer. Could you provide a PR with a failing test? I'll merge it right away.

**Comment by airblade** [comment]
No, sorry, it would take more time than I have available to figure out a test involving the entire Rails stack.

**Comment by daniel-rikowski** [comment]
Shouldn't this be catched by the existing tests already? After all just booting up the application triggers the problem.

**Comment by clemens** [comment]
It should – hence my question for a passing test. Maybe the require order is off or something.

**Comment by daniel-rikowski** [comment]
I invested a little time to investigate this.

The proper fix is adding this line to `delocalize.rb`:
```ruby
autoload :DelocalizableParameters, 'delocalize/delocalizable_parameters'
```
Creating a test is non-trivial, because the missing module is accessed from the Railtie, which is *not* loaded during tests. (Of course one could just add `assert defined?(DelocalizableParameters)` :hammer: )

In order to test the Railtie, it is actually necessary to create a small Rails environment from inside the test environment. Fortunately there's a gem for that which makes this a lot easier: https://github.com/pat/combustion


@clemens How do you specify the Rails version when running the tests locally? I had to make a lot of modifications to the gemspec, `Gemfile` and `test_helper.rb`, adding gems, shuffling requires and so on, in order to get the tests running with various Rails versions. I doubt this is the recommended method...

**Comment by clemens** [comment]
I've added the missing autoload [here](https://github.com/clemens/delocalize/commit/bd26d0286fc3796e5e07944c4704d4e4b5d2521d) and released 1.1.0. Let me know if there are still issues.

**Comment by airblade** [comment]
Thanks!

**Comment by lucasmncastro** [comment]
Thanks!

Lucas Castro
