### ISSUE TITLE
Demo application not available

### ISSUE THREAD

**Issue by SKoschnicke** [clemens/delocalize#84]
There are some links\* in the documentation pointing to https://github.com/clemens/delocalize_demo, which should be a demo application but is currently not available. Could this demo application be resurrected?

\* I found two: "Find a demo application here." at the start of the README.markdown and "Check out how this can be done in the demo app." under "Views" in the same file.

**Comment by clemens** [comment]
Thanks for reporting!

I've removed the demo repository when I released 1.0.0 since the approach was completely changed. If you feel inclined to writing a new one, I'm happy to point the link to a repository – just let me know. I'll remove the section for now to prevent confusion.

**Comment by clemens** [comment]
I was wrong back then since I had already updated the demo application to reflect the changes from 1.0 – so I've restored the demo app. Sorry about that.

**Comment by SKoschnicke** [comment]
Great, thank you! Maybe you should revert the [commit removing the second pointer to the demo app in the readme](https://github.com/clemens/delocalize/commit/e9095a93c18e37a5be3bbaf57e7f98890003d834), since I find a demo application very valuable.

**Comment by clemens** [comment]
I don't think that's necessary since there's a link in the readme anyway, right?

**Comment by SKoschnicke** [comment]
My concern was that somebody wouldn't notice that link because it appears further down in the readme. On the other hand the readme is quite short and one should it read completely anyway, so it's okay 😄
